import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Layout } from 'antd';
import HeaderCom from '../layout/Header';
import ContentCom from '../layout/Content';
import List from '../components/CardList';
import { PostCardProps } from '../components/DisplayCard';


const { Header, Footer, Content } = Layout;

const postList: PostCardProps[] = [1,2,3,4,5,6,7,8,9].map(i => {
  return { 
    title: 'While browsing for color palettes recently',
    desc: 'How it works is this: when you hover over a color',
  }}
)

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>yueliangjie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {/* <Header className={styles.header}>
          <HeaderCom />
        </Header> */}
        {/* <Content className={styles.main}>
          <List list={postList}/>
        </Content> */}
          <List list={postList}/>

        <Footer className={styles.footer}>
          {/* <footer className={styles.footer}> */}
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a>
          {/* </footer> */}
        </Footer>
      </Layout>
    </div>
  )
}

export default Home
