import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Layout } from 'antd';
import HeaderCom from '../layout/Header';
import ContentCom from '../layout/Content';
import List from '../components/CardList';
import { PostCardProps } from '../components/DisplayCard';
import { Provider } from 'react-redux';
import { store } from '../redux/store';

const { Header, Footer, Content } = Layout;

const postList: PostCardProps[] = [1,2,3,4,5,6,7,8,9].map(i => {
  return { 
    title: 'While browsing for color palettes recently',
    desc: 'How it works is this: when you hover over a color',
  }}
)

const Home: NextPage = () => {
  return (
    <Provider store={store}>
      <div className={styles.container}>
        <Head>
          <title>yueliangjie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout>
          <Header className={styles.header}>
            <HeaderCom />
          </Header>
          <Content className={styles.main}>
            <ContentCom>
              {/* <List list={postList}/> */}
              <div>建设中。。。</div>
            </ContentCom>
          </Content>
            {/* <List list={postList}/> */}

          <Footer className={styles.footer}>
            <a href='https://beian.miit.gov.cn/'>京ICP备2021036553号-1</a>
          </Footer>
        </Layout>
      </div>
    </Provider>
  )
}

export default Home
